<?php

/**
 * تجميع النصوص القابلة للتحرير من لوحة التحكم.
 * كل مجموعة تمثل قسماً أو صفحة، وتحتوي على المفاتيح (من ملفات الترجمة) مع وصف للمسؤول.
 */
return [
    'home' => [
        'label_ar' => 'الصفحة الرئيسية',
        'label_en' => 'Home Page',
        'items' => [
            'ui.hero_default_title' => ['label_ar' => 'عنوان البطل (السطر الأول)', 'label_en' => 'Hero title (line 1)'],
            'ui.hero_default_line2' => ['label_ar' => 'عنوان البطل (السطر الثاني)', 'label_en' => 'Hero title (line 2)'],
            'ui.hero_default_subtitle' => ['label_ar' => 'نص البطل التعريفي', 'label_en' => 'Hero subtitle'],
            'ui.our_projects' => ['label_ar' => 'عنوان قسم المشاريع', 'label_en' => 'Projects section title'],
            'ui.testimonials' => ['label_ar' => 'عنوان قسم الإشادة', 'label_en' => 'Testimonials title'],
            'ui.testimonials_empty' => ['label_ar' => 'رسالة عدم وجود إشادات', 'label_en' => 'Empty testimonials message'],
            'ui.success_network' => ['label_ar' => 'شارة شبكة النجاح', 'label_en' => 'Success network badge'],
            'ui.partners_heading' => ['label_ar' => 'عنوان قسم الشركاء', 'label_en' => 'Partners section title'],
            'ui.partners_subheading' => ['label_ar' => 'وصف قسم الشركاء', 'label_en' => 'Partners section subtitle'],
            'ui.view_all_partners' => ['label_ar' => 'زر استعراض الشركاء', 'label_en' => 'View partners button'],
            'ui.news_heading' => ['label_ar' => 'عنوان قسم الأخبار', 'label_en' => 'News section title'],
            'ui.browse_blog' => ['label_ar' => 'زر تصفح المدونة', 'label_en' => 'Browse blog button'],
            'ui.no_news' => ['label_ar' => 'رسالة عدم وجود أخبار', 'label_en' => 'No news message'],
            'ui.stat_scholarship' => ['label_ar' => 'إحصائية: المنح', 'label_en' => 'Stat: Scholarships'],
            'ui.stat_beneficiary' => ['label_ar' => 'إحصائية: المستفيدون', 'label_en' => 'Stat: Beneficiaries'],
            'ui.stat_partner' => ['label_ar' => 'إحصائية: الشركاء', 'label_en' => 'Stat: Partners'],
            'ui.stat_success_story' => ['label_ar' => 'إحصائية: قصص النجاح', 'label_en' => 'Stat: Success stories'],
            'ui.badge_training' => ['label_ar' => 'شارة: تدريب', 'label_en' => 'Badge: Training'],
            'ui.badge_hand_in_hand' => ['label_ar' => 'شارة: يد بيد', 'label_en' => 'Badge: Hand in hand'],
            'ui.badge_our_store' => ['label_ar' => 'شارة: متجرنا', 'label_en' => 'Badge: Our store'],
            'ui.badge_sustainability' => ['label_ar' => 'شارة: إستدامة', 'label_en' => 'Badge: Sustainability'],
            'ui.badge_student_fund' => ['label_ar' => 'شارة: صندوق الطلبة', 'label_en' => 'Badge: Student fund'],
            'ui.project_tamkeen' => ['label_ar' => 'بطاقة: مشروع تمكين', 'label_en' => 'Card: Tamkeen project'],
            'ui.project_tamkeen_desc' => ['label_ar' => 'وصف بطاقة تمكين', 'label_en' => 'Tamkeen card description'],
            'ui.trained_count' => ['label_ar' => 'تم تدريب:', 'label_en' => 'Trained:'],
            'ui.students' => ['label_ar' => 'طالب', 'label_en' => 'Students'],
            'ui.annual_goal' => ['label_ar' => 'الهدف السنوي:', 'label_en' => 'Annual goal:'],
            'ui.trainees' => ['label_ar' => 'متدرب', 'label_en' => 'Trainees'],
            'ui.training_details' => ['label_ar' => 'تفاصيل التدريب', 'label_en' => 'Training details'],
            'ui.project_kanani' => ['label_ar' => 'بطاقة: متجر كنعاني', 'label_en' => 'Card: Kanani store'],
            'ui.project_kanani_desc' => ['label_ar' => 'وصف بطاقة كنعاني', 'label_en' => 'Kanani card description'],
            'ui.provided_count' => ['label_ar' => 'تم تقديم:', 'label_en' => 'Provided:'],
            'ui.scholarships_count' => ['label_ar' => 'منحة', 'label_en' => 'Scholarships'],
            'ui.grants_goal' => ['label_ar' => 'الهدف السنوي:', 'label_en' => 'Grants goal:'],
            'ui.visit_store' => ['label_ar' => 'زيارة متجرنا', 'label_en' => 'Visit store'],
            'ui.project_parasols' => ['label_ar' => 'بطاقة: مشروع المظلات', 'label_en' => 'Card: Parasols project'],
            'ui.project_parasols_desc' => ['label_ar' => 'وصف بطاقة المظلات', 'label_en' => 'Parasols card description'],
            'ui.collected' => ['label_ar' => 'تم جمع:', 'label_en' => 'Collected:'],
            'ui.vacancy_rate' => ['label_ar' => 'نسبة المساحات الشاغرة:', 'label_en' => 'Vacancy rate:'],
            'ui.goal_reach' => ['label_ar' => 'الهدف', 'label_en' => 'Goal'],
            'ui.view_vacancies' => ['label_ar' => 'عرض الشواغر', 'label_en' => 'View vacancies'],
        ],
    ],
    'nav' => [
        'label_ar' => 'القائمة والتنقل',
        'label_en' => 'Navigation',
        'items' => [
            'ui.nav_home' => ['label_ar' => 'الرئيسية', 'label_en' => 'Home'],
            'ui.nav_about' => ['label_ar' => 'من نحن', 'label_en' => 'About'],
            'ui.nav_our_team' => ['label_ar' => 'فريقنا', 'label_en' => 'Our Team'],
            'ui.nav_projects' => ['label_ar' => 'مشاريعنا', 'label_en' => 'Our Projects'],
            'ui.nav_kanani' => ['label_ar' => 'مشروع كنعاني', 'label_en' => 'Kanani'],
            'ui.nav_tamkeen' => ['label_ar' => 'مشروع تمكين', 'label_en' => 'Tamkeen'],
            'ui.nav_parasols' => ['label_ar' => 'مشروع المظلات', 'label_en' => 'Parasols'],
            'ui.nav_grants' => ['label_ar' => 'المنح الدراسية', 'label_en' => 'Scholarships'],
            'ui.nav_partners' => ['label_ar' => 'شركاء النجاح', 'label_en' => 'Success Partners'],
            'ui.nav_news' => ['label_ar' => 'الأخبار', 'label_en' => 'News'],
            'ui.nav_lang_switch' => ['label_ar' => 'مفتاح تبديل اللغة', 'label_en' => 'Language switch label'],
            'ui.menu' => ['label_ar' => 'القائمة', 'label_en' => 'Menu'],
        ],
    ],
    'footer' => [
        'label_ar' => 'التذييل',
        'label_en' => 'Footer',
        'items' => [
            'ui.footer_desc' => ['label_ar' => 'وصف التذييل', 'label_en' => 'Footer description'],
            'ui.footer_about_heading' => ['label_ar' => 'عنوان: عن الجمعية', 'label_en' => 'About heading'],
            'ui.footer_programs_heading' => ['label_ar' => 'عنوان: برامجنا', 'label_en' => 'Programs heading'],
            'ui.footer_subscribe' => ['label_ar' => 'اشترك معنا', 'label_en' => 'Subscribe'],
            'ui.quick_links' => ['label_ar' => 'روابط سريعة', 'label_en' => 'Quick links'],
            'ui.contact_us' => ['label_ar' => 'تواصل معنا', 'label_en' => 'Contact us'],
            'ui.address' => ['label_ar' => 'العنوان', 'label_en' => 'Address'],
            'ui.newsletter' => ['label_ar' => 'النشرة الإخبارية', 'label_en' => 'Newsletter'],
            'ui.newsletter_desc' => ['label_ar' => 'وصف النشرة', 'label_en' => 'Newsletter description'],
            'ui.email_placeholder' => ['label_ar' => 'البريد (placeholder)', 'label_en' => 'Email placeholder'],
            'ui.follow_us' => ['label_ar' => 'تابعنا', 'label_en' => 'Follow us'],
            'ui.rights_reserved' => ['label_ar' => 'حقوق النشر', 'label_en' => 'Rights reserved'],
            'ui.privacy_policy' => ['label_ar' => 'سياسة الخصوصية', 'label_en' => 'Privacy policy'],
            'ui.terms_of_use' => ['label_ar' => 'شروط الاستخدام', 'label_en' => 'Terms of use'],
        ],
    ],
    'about' => [
        'label_ar' => 'صفحة من نحن',
        'label_en' => 'About Page',
        'items' => [
            'about.page_title' => ['label_ar' => 'عنوان الصفحة', 'label_en' => 'Page title'],
            'about.founder_badge' => ['label_ar' => 'شارة رسالة المؤسس', 'label_en' => 'Founder badge'],
            'about.founder_title' => ['label_ar' => 'عنوان كلمة المؤسس', 'label_en' => 'Founder title'],
            'about.founder_title_highlight' => ['label_ar' => 'تمييز عنوان المؤسس', 'label_en' => 'Founder title highlight'],
            'about.founder_quote' => ['label_ar' => 'اقتباس المؤسس', 'label_en' => 'Founder quote'],
            'about.founder_name' => ['label_ar' => 'اسم المؤسس', 'label_en' => 'Founder name'],
            'about.founder_role' => ['label_ar' => 'منصب المؤسس', 'label_en' => 'Founder role'],
            'about.watch_message' => ['label_ar' => 'زر شاهد الرسالة', 'label_en' => 'Watch message button'],
            'about.story_title' => ['label_ar' => 'عنوان قصة الجمعية', 'label_en' => 'Story title'],
            'about.story_desc' => ['label_ar' => 'وصف قصة الجمعية', 'label_en' => 'Story description'],
            'about.watch_story' => ['label_ar' => 'زر شاهد القصة', 'label_en' => 'Watch story button'],
            'about.identity_title' => ['label_ar' => 'عنوان هويتنا وقيمنا', 'label_en' => 'Identity title'],
            'about.identity_intro' => ['label_ar' => 'مقدمة الهوية', 'label_en' => 'Identity intro'],
            'about.cta_title' => ['label_ar' => 'عنوان دعوة الإجراء', 'label_en' => 'CTA title'],
            'about.cta_desc' => ['label_ar' => 'وصف دعوة الإجراء', 'label_en' => 'CTA description'],
            'about.volunteer_btn' => ['label_ar' => 'زر التطوع', 'label_en' => 'Volunteer button'],
            'about.donate_btn' => ['label_ar' => 'زر التبرع', 'label_en' => 'Donate button'],
        ],
    ],
    'partners' => [
        'label_ar' => 'صفحة شركاء النجاح',
        'label_en' => 'Success Partners Page',
        'items' => [
            'partners.page_title' => ['label_ar' => 'عنوان الصفحة', 'label_en' => 'Page title'],
            'partners.badge' => ['label_ar' => 'الشارة', 'label_en' => 'Badge'],
            'partners.hero_title' => ['label_ar' => 'عنوان البطل', 'label_en' => 'Hero title'],
            'partners.hero_title_highlight' => ['label_ar' => 'تمييز عنوان البطل', 'label_en' => 'Hero highlight'],
            'partners.hero_subtitle' => ['label_ar' => 'وصف البطل', 'label_en' => 'Hero subtitle'],
            'partners.cta_become' => ['label_ar' => 'كن شريكاً', 'label_en' => 'Become partner'],
            'partners.cta_report' => ['label_ar' => 'عرض التقرير', 'label_en' => 'View report'],
            'partners.stat1_label' => ['label_ar' => 'إحصائية 1', 'label_en' => 'Stat 1'],
            'partners.stat2_label' => ['label_ar' => 'إحصائية 2', 'label_en' => 'Stat 2'],
            'partners.stat3_label' => ['label_ar' => 'إحصائية 3', 'label_en' => 'Stat 3'],
            'partners.stat4_label' => ['label_ar' => 'إحصائية 4', 'label_en' => 'Stat 4'],
            'partners.section_title' => ['label_ar' => 'عنوان قسم الشركاء', 'label_en' => 'Partners section title'],
            'partners.section_subtitle' => ['label_ar' => 'وصف قسم الشركاء', 'label_en' => 'Section subtitle'],
            'partners.filter_company' => ['label_ar' => 'فلتر الشركات', 'label_en' => 'Company filter'],
            'partners.filter_individual' => ['label_ar' => 'فلتر الأفراد', 'label_en' => 'Individual filter'],
            'partners.no_partners' => ['label_ar' => 'لا يوجد شركاء', 'label_en' => 'No partners'],
            'partners.cta_title' => ['label_ar' => 'عنوان الدعوة', 'label_en' => 'CTA title'],
            'partners.cta_subtitle' => ['label_ar' => 'وصف الدعوة', 'label_en' => 'CTA subtitle'],
            'partners.cta_policy_pdf' => ['label_ar' => 'سياسات PDF', 'label_en' => 'Policy PDF'],
            'partners.cta_whatsapp' => ['label_ar' => 'واتساب', 'label_en' => 'WhatsApp'],
        ],
    ],
    'grants' => [
        'label_ar' => 'صفحة المنح',
        'label_en' => 'Grants Page',
        'items' => [
            'ui.grants_page_title' => ['label_ar' => 'عنوان صفحة المنح', 'label_en' => 'Grants page title'],
            'ui.grants_intro' => ['label_ar' => 'مقدمة المنح', 'label_en' => 'Grants intro'],
            'ui.grants_empty' => ['label_ar' => 'لا توجد منح', 'label_en' => 'No grants'],
            'ui.grants_vision_title_1' => ['label_ar' => 'رؤيتنا (سطر 1)', 'label_en' => 'Vision title 1'],
            'ui.grants_vision_title_2' => ['label_ar' => 'رؤيتنا (سطر 2)', 'label_en' => 'Vision title 2'],
            'ui.grants_vision_desc' => ['label_ar' => 'وصف الرؤية', 'label_en' => 'Vision description'],
            'ui.grants_vision_cta' => ['label_ar' => 'زر الرؤية', 'label_en' => 'Vision CTA'],
            'ui.grants_stat_annual' => ['label_ar' => 'إحصائية الدعم السنوي', 'label_en' => 'Annual stat'],
            'ui.grants_stat_active' => ['label_ar' => 'إحصائية المنح المفعلة', 'label_en' => 'Active stat'],
            'ui.apply_portal' => ['label_ar' => 'بوابة التقديم', 'label_en' => 'Apply portal'],
            'ui.apply_portal_intro' => ['label_ar' => 'مقدمة بوابة التقديم', 'label_en' => 'Portal intro'],
            'ui.open_for_apply' => ['label_ar' => 'متاح للتقديم', 'label_en' => 'Open for apply'],
            'ui.apply_ended' => ['label_ar' => 'انتهى التقديم', 'label_en' => 'Apply ended'],
            'ui.download_grants_pdf' => ['label_ar' => 'تحميل ملف المنحة', 'label_en' => 'Download PDF'],
            'ui.apply_details' => ['label_ar' => 'تفاصيل التقديم', 'label_en' => 'Apply details'],
            'ui.application_guide_title' => ['label_ar' => 'دليل خطوات التقديم', 'label_en' => 'Application guide title'],
        ],
    ],
    'news' => [
        'label_ar' => 'صفحة الأخبار',
        'label_en' => 'News Page',
        'items' => [
            'ui.news_archive_title' => ['label_ar' => 'عنوان أرشيف الأخبار', 'label_en' => 'News archive title'],
            'ui.news_archive_badge' => ['label_ar' => 'شارة الأرشيف', 'label_en' => 'Archive badge'],
            'ui.news_archive_subtitle' => ['label_ar' => 'وصف الأرشيف', 'label_en' => 'Archive subtitle'],
            'ui.no_news_found' => ['label_ar' => 'لا توجد أخبار', 'label_en' => 'No news found'],
            'ui.view_all_news' => ['label_ar' => 'عرض كل الأخبار', 'label_en' => 'View all news'],
            'ui.related_news' => ['label_ar' => 'أخبار ذات صلة', 'label_en' => 'Related news'],
            'ui.all_news' => ['label_ar' => 'كل الأخبار', 'label_en' => 'All news'],
            'ui.filter_results' => ['label_ar' => 'تصفية النتائج', 'label_en' => 'Filter results'],
        ],
    ],
    'kanani' => [
        'label_ar' => 'صفحة مشروع كنعاني',
        'label_en' => 'Kanani Project Page',
        'items' => [
            'kanani.page_title' => ['label_ar' => 'عنوان الصفحة', 'label_en' => 'Page title'],
            'kanani.badge_heritage' => ['label_ar' => 'شارة التراث', 'label_en' => 'Heritage badge'],
            'kanani.hero_title_line1' => ['label_ar' => 'عنوان البطل سطر 1', 'label_en' => 'Hero title line 1'],
            'kanani.hero_title_line2' => ['label_ar' => 'عنوان البطل سطر 2', 'label_en' => 'Hero title line 2'],
            'kanani.hero_subtitle' => ['label_ar' => 'وصف البطل', 'label_en' => 'Hero subtitle'],
            'kanani.hero_point1' => ['label_ar' => 'نقطة 1', 'label_en' => 'Point 1'],
            'kanani.hero_point2' => ['label_ar' => 'نقطة 2', 'label_en' => 'Point 2'],
            'kanani.hero_point3' => ['label_ar' => 'نقطة 3', 'label_en' => 'Point 3'],
            'kanani.discover_more' => ['label_ar' => 'اكتشف المزيد', 'label_en' => 'Discover more'],
            'kanani.stat1_label' => ['label_ar' => 'إحصائية 1', 'label_en' => 'Stat 1'],
            'kanani.stat2_label' => ['label_ar' => 'إحصائية 2', 'label_en' => 'Stat 2'],
            'kanani.stat3_label' => ['label_ar' => 'إحصائية 3', 'label_en' => 'Stat 3'],
            'kanani.gallery_title' => ['label_ar' => 'عنوان المعرض', 'label_en' => 'Gallery title'],
            'kanani.gallery_subtitle' => ['label_ar' => 'وصف المعرض', 'label_en' => 'Gallery subtitle'],
            'kanani.browse_all' => ['label_ar' => 'تصفح الكل', 'label_en' => 'Browse all'],
            'kanani.add_to_cart' => ['label_ar' => 'إضافة للسلة', 'label_en' => 'Add to cart'],
            'kanani.visit_full_store' => ['label_ar' => 'زيارة المتجر الكامل', 'label_en' => 'Visit full store'],
            'kanani.no_products' => ['label_ar' => 'لا توجد منتجات', 'label_en' => 'No products'],
            'kanani.cta_title' => ['label_ar' => 'عنوان الدعوة', 'label_en' => 'CTA title'],
            'kanani.cta_subtitle' => ['label_ar' => 'وصف الدعوة', 'label_en' => 'CTA subtitle'],
        ],
    ],
    'tamkeen' => [
        'label_ar' => 'صفحة مشروع تمكين',
        'label_en' => 'Tamkeen Project Page',
        'items' => [
            'tamkeen.page_title' => ['label_ar' => 'عنوان الصفحة', 'label_en' => 'Page title'],
            'tamkeen.badge' => ['label_ar' => 'شارة المبادرة', 'label_en' => 'Badge'],
            'tamkeen.hero_title_line1' => ['label_ar' => 'عنوان البطل سطر 1', 'label_en' => 'Hero title line 1'],
            'tamkeen.hero_title_line2' => ['label_ar' => 'عنوان البطل سطر 2', 'label_en' => 'Hero title line 2'],
            'tamkeen.hero_subtitle' => ['label_ar' => 'وصف البطل', 'label_en' => 'Hero subtitle'],
            'tamkeen.partner_join' => ['label_ar' => 'انضم كشريك', 'label_en' => 'Join as partner'],
            'tamkeen.browse_guide' => ['label_ar' => 'تصفح دليل الشركاء', 'label_en' => 'Browse guide'],
            'tamkeen.stat1_label' => ['label_ar' => 'إحصائية 1', 'label_en' => 'Stat 1'],
            'tamkeen.stat1_desc' => ['label_ar' => 'وصف إحصائية 1', 'label_en' => 'Stat 1 description'],
            'tamkeen.stat2_label' => ['label_ar' => 'إحصائية 2', 'label_en' => 'Stat 2'],
            'tamkeen.stat2_desc' => ['label_ar' => 'وصف إحصائية 2', 'label_en' => 'Stat 2 description'],
            'tamkeen.stat3_label' => ['label_ar' => 'إحصائية 3', 'label_en' => 'Stat 3'],
            'tamkeen.stat3_desc' => ['label_ar' => 'وصف إحصائية 3', 'label_en' => 'Stat 3 description'],
            'tamkeen.partners_heading' => ['label_ar' => 'عنوان قسم الشركاء', 'label_en' => 'Partners heading'],
            'tamkeen.partners_subtitle' => ['label_ar' => 'وصف قسم الشركاء', 'label_en' => 'Partners subtitle'],
            'tamkeen.filter_label' => ['label_ar' => 'تصفية حسب القطاع', 'label_en' => 'Filter label'],
            'tamkeen.filter_all' => ['label_ar' => 'جميع القطاعات', 'label_en' => 'All sectors'],
            'tamkeen.cta_title' => ['label_ar' => 'عنوان الدعوة', 'label_en' => 'CTA title'],
            'tamkeen.cta_subtitle' => ['label_ar' => 'وصف الدعوة', 'label_en' => 'CTA subtitle'],
            'tamkeen.cta_button' => ['label_ar' => 'زر التسجيل', 'label_en' => 'CTA button'],
        ],
    ],
    'parasols' => [
        'label_ar' => 'صفحة مشروع المظلات',
        'label_en' => 'Parasols Project Page',
        'items' => [
            'parasols.page_title' => ['label_ar' => 'عنوان الصفحة', 'label_en' => 'Page title'],
            'parasols.badge' => ['label_ar' => 'شارة المبادرة', 'label_en' => 'Badge'],
            'parasols.hero_title' => ['label_ar' => 'عنوان البطل', 'label_en' => 'Hero title'],
            'parasols.hero_subtitle' => ['label_ar' => 'وصف البطل', 'label_en' => 'Hero subtitle'],
            'parasols.cta_primary' => ['label_ar' => 'اكتشف المساحات', 'label_en' => 'Discover spaces'],
            'parasols.cta_secondary' => ['label_ar' => 'كيف يعمل المشروع؟', 'label_en' => 'How it works'],
            'parasols.stat1_label' => ['label_ar' => 'إحصائية 1', 'label_en' => 'Stat 1'],
            'parasols.stat2_label' => ['label_ar' => 'إحصائية 2', 'label_en' => 'Stat 2'],
            'parasols.stat3_label' => ['label_ar' => 'إحصائية 3', 'label_en' => 'Stat 3'],
            'parasols.stat4_label' => ['label_ar' => 'إحصائية 4', 'label_en' => 'Stat 4'],
            'parasols.section_title' => ['label_ar' => 'عنوان المساحات', 'label_en' => 'Section title'],
            'parasols.status_available' => ['label_ar' => 'متاحة للحجز', 'label_en' => 'Available'],
            'parasols.no_spaces' => ['label_ar' => 'لا توجد مساحات', 'label_en' => 'No spaces'],
            'parasols.cta_title' => ['label_ar' => 'عنوان الدعوة', 'label_en' => 'CTA title'],
            'parasols.cta_subtitle' => ['label_ar' => 'وصف الدعوة', 'label_en' => 'CTA subtitle'],
            'parasols.cta_contact' => ['label_ar' => 'تواصل معنا', 'label_en' => 'Contact us'],
        ],
    ],
    'team' => [
        'label_ar' => 'صفحة فريقنا',
        'label_en' => 'Team Page',
        'items' => [
            'team.page_title' => ['label_ar' => 'عنوان الصفحة', 'label_en' => 'Page title'],
            'team.page_intro' => ['label_ar' => 'مقدمة الصفحة', 'label_en' => 'Page intro'],
            'team.chairperson_name' => ['label_ar' => 'اسم رئيسة مجلس الإدارة', 'label_en' => 'Chairperson name'],
            'team.chairperson_position' => ['label_ar' => 'منصب رئيسة مجلس الإدارة', 'label_en' => 'Chairperson position'],
            'team.chairperson_title' => ['label_ar' => 'كلمة رئيسة', 'label_en' => 'Chairperson title'],
            'team.chairperson_title_highlight' => ['label_ar' => 'تمييز العنوان', 'label_en' => 'Title highlight'],
            'team.chairperson_message_1' => ['label_ar' => 'رسالة 1', 'label_en' => 'Message 1'],
            'team.chairperson_message_2' => ['label_ar' => 'رسالة 2', 'label_en' => 'Message 2'],
            'team.chairperson_message_3' => ['label_ar' => 'رسالة 3', 'label_en' => 'Message 3'],
            'team.board_heading' => ['label_ar' => 'مجلس الإدارة', 'label_en' => 'Board heading'],
            'team.staff_heading' => ['label_ar' => 'فريق العمل', 'label_en' => 'Staff heading'],
            'team.no_board' => ['label_ar' => 'لا يوجد مجلس', 'label_en' => 'No board'],
            'team.no_staff' => ['label_ar' => 'لا يوجد فريق', 'label_en' => 'No staff'],
        ],
    ],
    'statistics' => [
        'label_ar' => 'أرقام الإحصائيات',
        'label_en' => 'Statistics Numbers',
        'items' => [
            'stats.partners_stat1' => ['label_ar' => 'شركاء النجاح - إجمالي الشركاء (فارغ=من قاعدة البيانات)', 'label_en' => 'Partners - total partners (empty=from DB)'],
            'stats.partners_stat2' => ['label_ar' => 'شركاء النجاح - طلاب مستفيدون', 'label_en' => 'Partners - beneficiaries'],
            'stats.partners_stat3' => ['label_ar' => 'شركاء النجاح - مشاريع ممولة', 'label_en' => 'Partners - funded projects'],
            'stats.partners_stat4' => ['label_ar' => 'شركاء النجاح - نمو الشراكات', 'label_en' => 'Partners - growth'],
            'stats.grants_stat_annual' => ['label_ar' => 'المنح - إجمالي الدعم السنوي ($)', 'label_en' => 'Grants - annual support total'],
            'stats.grants_stat_active' => ['label_ar' => 'المنح - منح مفعلة (فارغ=من قاعدة البيانات)', 'label_en' => 'Grants - active grants (empty=from DB)'],
            'stats.tamkeen_stat1' => ['label_ar' => 'تمكين - طالب مستفيد (فارغ=من قاعدة البيانات)', 'label_en' => 'Tamkeen - beneficiaries (empty=from DB)'],
            'stats.tamkeen_stat2' => ['label_ar' => 'تمكين - شريك استراتيجي (فارغ=من قاعدة البيانات)', 'label_en' => 'Tamkeen - partners (empty=from DB)'],
            'stats.tamkeen_stat3' => ['label_ar' => 'تمكين - ساعة تدريبية', 'label_en' => 'Tamkeen - training hours'],
        ],
    ],
    'legal' => [
        'label_ar' => 'السياسات والشروط',
        'label_en' => 'Legal & Policies',
        'items' => [
            'legal.privacy.title' => ['label_ar' => 'عنوان سياسة الخصوصية', 'label_en' => 'Privacy title'],
            'legal.privacy.intro' => ['label_ar' => 'مقدمة الخصوصية', 'label_en' => 'Privacy intro'],
            'legal.terms.title' => ['label_ar' => 'عنوان شروط الاستخدام', 'label_en' => 'Terms title'],
            'legal.terms.intro' => ['label_ar' => 'مقدمة الشروط', 'label_en' => 'Terms intro'],
        ],
    ],
    'general' => [
        'label_ar' => 'نصوص عامة',
        'label_en' => 'General',
        'items' => [
            'ui.site_name' => ['label_ar' => 'اسم الموقع', 'label_en' => 'Site name'],
            'ui.donate_now' => ['label_ar' => 'تبرع الآن', 'label_en' => 'Donate now'],
            'ui.read_more' => ['label_ar' => 'إقرأ المزيد', 'label_en' => 'Read more'],
            'ui.details' => ['label_ar' => 'التفاصيل', 'label_en' => 'Details'],
            'ui.view_all' => ['label_ar' => 'استعرض الكل', 'label_en' => 'View all'],
            'ui.annual_report' => ['label_ar' => 'التقرير السنوي', 'label_en' => 'Annual report'],
            'ui.link_copied' => ['label_ar' => 'تم نسخ الرابط', 'label_en' => 'Link copied'],
            'ui.copy_link' => ['label_ar' => 'انسخ الرابط', 'label_en' => 'Copy link'],
        ],
    ],
];
